"""restructure_role_tables

Revision ID: f139458176db
Revises: a6035079f22e
Create Date: 2025-09-30 11:37:00.545669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f139458176db'
down_revision: Union[str, None] = 'a6035079f22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_course_role_id'), 'course_role', ['id'], unique=False)
    op.create_table('primary_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_primary_role_id'), 'primary_role', ['id'], unique=False)
    
    # Seed primary roles
    op.execute("""
        INSERT INTO primary_role (id, name) VALUES 
        (1, 'administrator'),
        (2, 'staff'),
        (3, 'student')
    """)
    
    # Seed course roles
    op.execute("""
        INSERT INTO course_role (id, name) VALUES 
        (1, 'convener'),
        (2, 'facilitator'),
        (3, 'student')
    """)
    
    # Drop foreign key constraints before dropping the role table
    op.drop_constraint('user_primary_role_id_fkey', 'user', type_='foreignkey')
    op.drop_constraint('user_course_role_role_id_fkey', 'user_course_role', type_='foreignkey')
    
    # Now we can safely drop the role table
    op.drop_table('role')
    op.alter_column('assessment', 'upload_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assessment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assessment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('course', 'teacher_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('course', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('unique_course_title_code', 'course', type_='unique')
    op.create_unique_constraint(None, 'course', ['code'])
    op.drop_index('ix_mark_query_assessment_id', table_name='mark_query')
    op.drop_index('ix_mark_query_status', table_name='mark_query')
    op.drop_index('ix_mark_query_student_id', table_name='mark_query')
    op.alter_column('question', 'memo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('question', 'marking_note',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('question', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('question', 'updated_memo_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('unique_question_number_per_assessment', 'question', type_='unique')
    op.create_unique_constraint('uq_question_number_per_assessment', 'question', ['assessment_id', 'question_number'])
    op.alter_column('question_result', 'comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('question_result', 'annotation_file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('question_result', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('question_result', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('unique_question_result_per_student', 'question_result', type_='unique')
    op.create_index('uq_question_result_assessment_student_question', 'question_result', ['assessment_id', 'student_id', 'question_id'], unique=True)
    op.alter_column('uploaded_file', 'answer_sheet_file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('uploaded_file', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('unique_assessment_student_upload', 'uploaded_file', type_='unique')
    op.create_index('uq_uploaded_file_assessment_student', 'uploaded_file', ['assessment_id', 'student_id'], unique=True)
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user', 'primary_role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_constraint('user_student_number_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_student_number'), 'user', ['student_number'], unique=True)
    op.create_foreign_key(None, 'user', 'primary_role', ['primary_role_id'], ['id'])
    op.drop_column('user', 'primary_role')
    op.add_column('user_course_role', sa.Column('course_role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_course_role', 'course_role', ['course_role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_course_role', 'role_id')
    op.drop_column('user_course_role', 'is_convener')
    op.drop_column('user_course_role', 'course_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_course_role', sa.Column('course_role', postgresql.ENUM('CONVENER', 'FACILITATOR', 'STUDENT', name='courserole'), server_default=sa.text("'STUDENT'::courserole"), autoincrement=False, nullable=False))
    op.add_column('user_course_role', sa.Column('is_convener', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_course_role', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_course_role', type_='foreignkey')
    op.create_foreign_key('user_course_role_role_id_fkey', 'user_course_role', 'role', ['role_id'], ['id'])
    op.drop_column('user_course_role', 'course_role_id')
    op.add_column('user', sa.Column('primary_role', postgresql.ENUM('ADMINISTRATOR', 'TEACHER', 'STUDENT', name='primaryrole'), server_default=sa.text("'STUDENT'::primaryrole"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_primary_role_id_fkey', 'user', 'role', ['primary_role_id'], ['id'])
    op.drop_index(op.f('ix_user_student_number'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_student_number_key', 'user', ['student_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('user_email_key', 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'primary_role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('uq_uploaded_file_assessment_student', table_name='uploaded_file')
    op.create_unique_constraint('unique_assessment_student_upload', 'uploaded_file', ['assessment_id', 'student_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('uploaded_file', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('uploaded_file', 'answer_sheet_file_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('uq_question_result_assessment_student_question', table_name='question_result')
    op.create_unique_constraint('unique_question_result_per_student', 'question_result', ['assessment_id', 'student_id', 'question_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('question_result', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('question_result', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('question_result', 'annotation_file_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('question_result', 'comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_question_number_per_assessment', 'question', type_='unique')
    op.create_unique_constraint('unique_question_number_per_assessment', 'question', ['assessment_id', 'question_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('question', 'updated_memo_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('question', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('question', 'marking_note',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('question', 'memo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('ix_mark_query_student_id', 'mark_query', ['student_id'], unique=False)
    op.create_index('ix_mark_query_status', 'mark_query', ['status'], unique=False)
    op.create_index('ix_mark_query_assessment_id', 'mark_query', ['assessment_id'], unique=False)
    op.drop_constraint(None, 'course', type_='unique')
    op.create_unique_constraint('unique_course_title_code', 'course', ['title', 'code'], postgresql_nulls_not_distinct=False)
    op.alter_column('course', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('course', 'teacher_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('assessment', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assessment', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assessment', 'upload_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='role_pkey'),
    sa.UniqueConstraint('name', name='role_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_primary_role_id'), table_name='primary_role')
    op.drop_table('primary_role')
    op.drop_index(op.f('ix_course_role_id'), table_name='course_role')
    op.drop_table('course_role')
    # ### end Alembic commands ###
