-- ========================================
-- Role Table
-- ========================================
CREATE TABLE "role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR UNIQUE NOT NULL
);

-- Seed Roles with IDs
INSERT INTO role (id, name) VALUES (1, 'teacher'), (2, 'ta'), (3, 'student'), (4, 'admin');

-- ========================================
-- User Table
-- ========================================
CREATE TABLE "user" (
  "id" UUID PRIMARY KEY,
  "first_name" VARCHAR NOT NULL,
  "last_name" VARCHAR NOT NULL,
  "email" VARCHAR UNIQUE NOT NULL,
  "student_number" VARCHAR UNIQUE,
  "password_hash" VARCHAR NOT NULL,
  "primary_role_id" INT REFERENCES role(id),
  "is_admin" BOOLEAN DEFAULT FALSE,
  "created_at" TIMESTAMP DEFAULT now(),
  "updated_at" TIMESTAMP DEFAULT now()
);

-- ========================================
-- Course Table
-- ========================================
CREATE TABLE "course" (
  "id" UUID PRIMARY KEY,
  "title" VARCHAR NOT NULL,
  "teacher_id" UUID REFERENCES "user" ("id"),
  "code" VARCHAR,
  "created_at" TIMESTAMP DEFAULT now(),
  CONSTRAINT unique_course_title_code UNIQUE ("title", "code")
);

-- ========================================
-- User-Course Role Join Table
-- ========================================
CREATE TABLE "user_course_role" (
  "user_id" UUID NOT NULL,
  "course_id" UUID NOT NULL,
  "role_id" INT NOT NULL,
  PRIMARY KEY ("user_id", "course_id", "role_id"),
  FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("course_id") REFERENCES "course" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("role_id") REFERENCES "role" ("id")
);

-- ========================================
-- Assessment Table
-- ========================================
CREATE TABLE "assessment" (
  "id" UUID PRIMARY KEY,
  "title" VARCHAR NOT NULL,
  "course_id" UUID NOT NULL,
  "question_paper_file_path" TEXT,
  "upload_date" TIMESTAMP DEFAULT now(),
  "created_at" TIMESTAMP DEFAULT now(),
  "updated_at" TIMESTAMP DEFAULT now(),
  CONSTRAINT fk_assessment_course FOREIGN KEY ("course_id") REFERENCES "course" ("id") ON DELETE CASCADE
);

-- ========================================
-- Uploaded File Table
-- ========================================
CREATE TABLE "uploaded_file" (
  "id" UUID PRIMARY KEY,
  "assessment_id" UUID NOT NULL,
  "student_id" UUID NOT NULL,
  "answer_sheet_file_path" TEXT NOT NULL,
  "uploaded_by" UUID NOT NULL,
  "uploaded_at" TIMESTAMP DEFAULT now(),
  FOREIGN KEY ("assessment_id") REFERENCES "assessment" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("student_id") REFERENCES "user" ("id"),
  FOREIGN KEY ("uploaded_by") REFERENCES "user" ("id"),
  CONSTRAINT unique_assessment_student_upload UNIQUE ("assessment_id", "student_id")
);

-- ========================================
-- Question Table
-- ========================================
CREATE TABLE "question" (
  "id" UUID PRIMARY KEY,
  "assessment_id" UUID NOT NULL,
  "question_number" VARCHAR NOT NULL,
  "max_marks" FLOAT,
  "increment" FLOAT,
  "memo" TEXT,
  "marking_note" TEXT,
  "page_number" INT,
  "x" FLOAT,
  "y" FLOAT,
  "width" FLOAT,
  "height" FLOAT,
  "created_at" TIMESTAMP DEFAULT now(),
  "updated_memo_at" TIMESTAMP DEFAULT now(),
  FOREIGN KEY ("assessment_id") REFERENCES "assessment" ("id") ON DELETE CASCADE,
  CONSTRAINT unique_question_number_per_assessment UNIQUE ("assessment_id", "question_number")
);

-- ========================================
-- Question Result Table
-- ========================================
CREATE TABLE "question_result" (
  "id" UUID PRIMARY KEY,
  "student_id" UUID NOT NULL,
  "assessment_id" UUID NOT NULL,
  "question_id" UUID NOT NULL,
  "marker_id" UUID NOT NULL,
  "mark" FLOAT,
  "comment" TEXT,
  "annotation_file_path" TEXT,
  "created_at" TIMESTAMP DEFAULT now(),
  "updated_at" TIMESTAMP DEFAULT now(),
  FOREIGN KEY ("student_id") REFERENCES "user" ("id"),
  FOREIGN KEY ("assessment_id") REFERENCES "assessment" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("question_id") REFERENCES "question" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("marker_id") REFERENCES "user" ("id"),
  CONSTRAINT unique_question_result_per_student UNIQUE ("assessment_id", "student_id", "question_id")
);
