--
-- PostgreSQL database dump
--

\restrict vQMHauClklBKKcOVAhGkJIsNTsC6A72hvQ9UciMcnHX8Jhwh4ZTOYdlsfxdZl5X

-- Dumped from database version 14.19 (Homebrew)
-- Dumped by pg_dump version 14.19 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: rianmostert
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


ALTER TABLE public.alembic_version OWNER TO rianmostert;

--
-- Name: assessment; Type: TABLE; Schema: public; Owner: rianmostert
--

CREATE TABLE public.assessment (
    id uuid NOT NULL,
    title character varying NOT NULL,
    course_id uuid NOT NULL,
    question_paper_file_path text,
    upload_date timestamp without time zone DEFAULT now(),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    published boolean DEFAULT false NOT NULL
);


ALTER TABLE public.assessment OWNER TO rianmostert;

--
-- Name: course; Type: TABLE; Schema: public; Owner: rianmostert
--

CREATE TABLE public.course (
    id uuid NOT NULL,
    title character varying NOT NULL,
    teacher_id uuid,
    code character varying,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.course OWNER TO rianmostert;

--
-- Name: question; Type: TABLE; Schema: public; Owner: rianmostert
--

CREATE TABLE public.question (
    id uuid NOT NULL,
    assessment_id uuid NOT NULL,
    question_number character varying NOT NULL,
    max_marks double precision,
    increment double precision,
    memo text,
    marking_note text,
    page_number integer,
    x double precision,
    y double precision,
    width double precision,
    height double precision,
    created_at timestamp without time zone DEFAULT now(),
    updated_memo_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.question OWNER TO rianmostert;

--
-- Name: question_result; Type: TABLE; Schema: public; Owner: rianmostert
--

CREATE TABLE public.question_result (
    id uuid NOT NULL,
    student_id uuid NOT NULL,
    assessment_id uuid NOT NULL,
    question_id uuid NOT NULL,
    marker_id uuid NOT NULL,
    mark double precision,
    comment text,
    annotation_file_path text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.question_result OWNER TO rianmostert;

--
-- Name: role; Type: TABLE; Schema: public; Owner: rianmostert
--

CREATE TABLE public.role (
    id integer NOT NULL,
    name character varying NOT NULL
);


ALTER TABLE public.role OWNER TO rianmostert;

--
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: rianmostert
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: uploaded_file; Type: TABLE; Schema: public; Owner: rianmostert
--

CREATE TABLE public.uploaded_file (
    id uuid NOT NULL,
    assessment_id uuid NOT NULL,
    student_id uuid NOT NULL,
    answer_sheet_file_path text NOT NULL,
    uploaded_by uuid NOT NULL,
    uploaded_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.uploaded_file OWNER TO rianmostert;

--
-- Name: user; Type: TABLE; Schema: public; Owner: rianmostert
--

CREATE TABLE public."user" (
    id uuid NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    email character varying NOT NULL,
    student_number character varying,
    password_hash character varying NOT NULL,
    primary_role_id integer,
    is_admin boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public."user" OWNER TO rianmostert;

--
-- Name: user_course_role; Type: TABLE; Schema: public; Owner: rianmostert
--

CREATE TABLE public.user_course_role (
    user_id uuid NOT NULL,
    course_id uuid NOT NULL,
    role_id integer NOT NULL,
    is_convener boolean DEFAULT false NOT NULL
);


ALTER TABLE public.user_course_role OWNER TO rianmostert;

--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: assessment assessment_pkey; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.assessment
    ADD CONSTRAINT assessment_pkey PRIMARY KEY (id);


--
-- Name: course course_pkey; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (id);


--
-- Name: question question_pkey; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_pkey PRIMARY KEY (id);


--
-- Name: question_result question_result_pkey; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.question_result
    ADD CONSTRAINT question_result_pkey PRIMARY KEY (id);


--
-- Name: role role_name_key; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_name_key UNIQUE (name);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: uploaded_file unique_assessment_student_upload; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.uploaded_file
    ADD CONSTRAINT unique_assessment_student_upload UNIQUE (assessment_id, student_id);


--
-- Name: course unique_course_title_code; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT unique_course_title_code UNIQUE (title, code);


--
-- Name: question unique_question_number_per_assessment; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT unique_question_number_per_assessment UNIQUE (assessment_id, question_number);


--
-- Name: question_result unique_question_result_per_student; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.question_result
    ADD CONSTRAINT unique_question_result_per_student UNIQUE (assessment_id, student_id, question_id);


--
-- Name: uploaded_file uploaded_file_pkey; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.uploaded_file
    ADD CONSTRAINT uploaded_file_pkey PRIMARY KEY (id);


--
-- Name: user_course_role user_course_role_pkey; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.user_course_role
    ADD CONSTRAINT user_course_role_pkey PRIMARY KEY (user_id, course_id, role_id);


--
-- Name: user user_email_key; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_key UNIQUE (email);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: user user_student_number_key; Type: CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_student_number_key UNIQUE (student_number);


--
-- Name: course course_teacher_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public."user"(id);


--
-- Name: assessment fk_assessment_course; Type: FK CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.assessment
    ADD CONSTRAINT fk_assessment_course FOREIGN KEY (course_id) REFERENCES public.course(id) ON DELETE CASCADE;


--
-- Name: question question_assessment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessment(id) ON DELETE CASCADE;


--
-- Name: question_result question_result_assessment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.question_result
    ADD CONSTRAINT question_result_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessment(id) ON DELETE CASCADE;


--
-- Name: question_result question_result_marker_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.question_result
    ADD CONSTRAINT question_result_marker_id_fkey FOREIGN KEY (marker_id) REFERENCES public."user"(id);


--
-- Name: question_result question_result_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.question_result
    ADD CONSTRAINT question_result_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.question(id) ON DELETE CASCADE;


--
-- Name: question_result question_result_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.question_result
    ADD CONSTRAINT question_result_student_id_fkey FOREIGN KEY (student_id) REFERENCES public."user"(id);


--
-- Name: uploaded_file uploaded_file_assessment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.uploaded_file
    ADD CONSTRAINT uploaded_file_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessment(id) ON DELETE CASCADE;


--
-- Name: uploaded_file uploaded_file_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.uploaded_file
    ADD CONSTRAINT uploaded_file_student_id_fkey FOREIGN KEY (student_id) REFERENCES public."user"(id);


--
-- Name: uploaded_file uploaded_file_uploaded_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.uploaded_file
    ADD CONSTRAINT uploaded_file_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public."user"(id);


--
-- Name: user_course_role user_course_role_course_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.user_course_role
    ADD CONSTRAINT user_course_role_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.course(id) ON DELETE CASCADE;


--
-- Name: user_course_role user_course_role_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.user_course_role
    ADD CONSTRAINT user_course_role_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- Name: user_course_role user_course_role_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public.user_course_role
    ADD CONSTRAINT user_course_role_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: user user_primary_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: rianmostert
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_primary_role_id_fkey FOREIGN KEY (primary_role_id) REFERENCES public.role(id);


--
-- PostgreSQL database dump complete
--

\unrestrict vQMHauClklBKKcOVAhGkJIsNTsC6A72hvQ9UciMcnHX8Jhwh4ZTOYdlsfxdZl5X

