"""Add batch_id to mark_query table

Revision ID: 3c244b94e6e5
Revises: ba6b968346bc
Create Date: 2025-10-01 09:15:52.868253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c244b94e6e5'
down_revision: Union[str, None] = 'ba6b968346bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mark_query', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_mark_query_batch_id'), 'mark_query', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mark_query_batch_id'), table_name='mark_query')
    op.drop_column('mark_query', 'batch_id')
    # ### end Alembic commands ###
